
precision_thresholds:
  coarse: 0.01
  low: 0.1
  medium: 0.4
  high: 0.6
  saturated: 20.0

zoom:
  strategy: "percentile" # "percentile" or "rate"
  global_xb_fail_threshold: 0.5
  global_xb_fail_count: 2
  coarse:
    local_xb_fail_count: 2
    parameter_zoom_rate: 0.2
    density_growth_rate: 0.05
    zoom_percentile: 0.98
    min_points_per_iteration: 10
    no_improvement_max: 2
    small_improvement_max: 3
    small_improvement_frac: 0.2
  low:
    local_xb_fail_count: 2
    parameter_zoom_rate: 0.1
    density_growth_rate: 0.1
    zoom_percentile: 0.98
    min_points_per_iteration: 15
    no_improvement_max: 2
    small_improvement_max: 3
    small_improvement_frac: 0.1
  medium:
    local_xb_fail_threshold: 0.05
    local_xb_fail_count: 3
    parameter_zoom_rate: 0.05
    density_growth_rate: 0.2
    zoom_percentile: 0.95
    min_points_per_iteration: 25
    no_improvement_max: 3
    small_improvement_max: 4
    small_improvement_frac: 0.05
  high:
    local_xb_fail_count: 5
    parameter_zoom_rate: 0.02
    density_growth_rate: 0.5
    zoom_percentile: 0.9
    min_points_per_iteration: 100
    no_improvement_max: 4
    small_improvement_max: 5
    small_improvement_frac: 0.02

meanshift:
  # Proportion of total volume to use for scan volume
  scan_perc: 0.1
  # Number of points to sample for each iteration
  num_points: 50
  # Mode to use for stop condition, 0 = test point, 1 = prev point
  stop_mode: 1
  # Threshold fractional change in any parameter to continue optimization
  stop_sensitivity_par: 0.05
  # Threshold fractional change in xb to continue optimization
  stop_sensitivity_xb: 0.05
  # Max number of small steps used for stopping conditions
  max_small_steps: 3
  # Exponent for weighting (higher means greater pull from high xb points)
  z_exp: 1.0
  # Flag to control whether z_exp is adaptively modified
  use_adaptive_z_exp: True
  # alpha value for the coefficient variation calculation (higher means more sensitivity to bumps)
  z_exp_alpha: 0.9
