
ScannerS:
  min_points_per_job: 5
  timeout: 10
  #seed: 123456 # random seed for ScannerS - should be commented out except for development

MultiProcessing:
  cpu_reserve: -1 # How many CPUs to reserve for the main process, -1 means reserving the default number of CPUs

prescan:
  chunk_size: 1000

bounds:
  min_chunk_size: 100 # minimum number of dataframe rows in a bounds check

HTCondor:
  num_cpus: 8 # default number of CPUs to request
  job_length: "espresso" # default job runtime (espresso, microcentury, longlunch, etc.) more details at https://batchdocs.web.cern.ch/local/submit.html

params:
  #seed: 123456 # random seed for ParamRange.random_point() - should be commented out except for development
