
model:
  model_name: "TRSMBroken"

width:
  max_width_H: 0.15
  max_width_S: 0.15
  max_width_X: 0.15

prescan:
  chunk_size: 1000

scan:
  default_prescan_points: 10000
  default_starting_points: 10000

zoom:
  strategy: "percentile" # "percentile" or "rate"
  parameter_zoom_rate: 0.05
  density_growth_rate: 0.2
  zoom_percentile: 0.95
  min_points_per_iteration: 20

meanshift:
  # Proportion of total volume to use for scan volume
  scan_perc: 0.1
  # Number of points to sample for each iteration
  num_points: 50
  # Mode to use for stop condition, 0 = test point, 1 = prev point
  stop_mode: 1
  # Threshold fractional change in any parameter to continue optimization
  stop_sensitivity_par: 0.05
  # Threshold fractional change in xb to continue optimization
  stop_sensitivity_xb: 0.05
  # Max number of small steps used for stopping conditions
  max_small_steps: 3
  # Method of generating starting points, try "random" or "pair"
  points_gen: 'random'
  # "pair" points coefficient to use for generating subsequent points as a percentage subtracted from the previous point
  pair_points_coeff: 0.005
  # Exponent for weighting (higher means greater pull from high xb points)
  z_exp: 1.0
  # Flag to control whether z_exp is adaptively modified
  use_adaptive_z_exp: True
  # alpha value for the coefficient variation calculation (higher means more sensitivity to bumps)
  z_exp_alpha: 0.9
